POST http://localhost/password
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMzMzcwMjc0LCJ1c2VySWQiOjF9.jnrzpXkzK0NQv1u7Hxq5MBkyO1DJbENvnRgRxJcNKEs
Content-Type: application/json

{
  "old_password": "1122001120012s111",
  "new_password": "as21321321321312"
}